### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by ShafiqSadat** [restfb/restfb-examples#10]
```

Exception in thread "main" com.restfb.exception.FacebookOAuthException: Received Facebook error response of type OAuthException: (#200) Requires either publish_to_groups permission and app being installed in the group, or manage_pages and publish_pages as an admin with sufficient administrative permission (code 200, subcode null) 'null - null'
	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator$DefaultGraphFacebookExceptionMapper.exceptionForTypeAndMessage(DefaultFacebookExceptionGenerator.java:174)
	at com.restfb.exception.generator.DefaultFacebookExceptionGenerator.throwFacebookResponseStatusExceptionIfNecessary(DefaultFacebookExceptionGenerator.java:59)
	at com.restfb.DefaultFacebookClient.makeRequestAndProcessResponse(DefaultFacebookClient.java:918)
	at com.restfb.DefaultFacebookClient.makeRequest(DefaultFacebookClient.java:836)
	at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:389)
	at com.restfb.DefaultFacebookClient.publish(DefaultFacebookClient.java:414)```

Someone has a simple example to use the new version
I looked at YouTube but did not
A simple example to post a text in a new version 2.10

**Comment by nbartels** [comment]
Your access token need some permissions, as the error message says. 
- `publish_to_groups` if you like to send your message to a group. 
- Or `manage_pages` _and_ `publish_pages` if you like to post as a page. 
- You cannot post to the user feed, because Facebook removed this function some months ago.

So, can you elaborate the problem a bit more.

**Comment by ShafiqSadat** [comment]
But my access token has all the access!

**Comment by velykov** [comment]
Publish to me/feed is depricated, so example 'Feed publishing" is not work

**Comment by nbartels** [comment]
Yes, we should renew the examples ... sadly Facebook is trimming the access to their API from version to version. So a current example can show only some poor requests.
